version: "3"

services:
  firebase:
    build:
      context: ./firebase
    volumes:
      - ./firebase/emulators/:/opt/workspace:cached
      - ./firebase/bin/:/root/.cache:cached
      - ./firebase/config/:/root/.config:cached
    ports:
      - 4000:4000 # Emulator Suite UI
      - 9000:9000 # Realtime Database
    working_dir: /opt/workspace
    command: bash
    tty: true
